# This GitHub Actions workflow adapted from https://www.getzola.org/documentation/deployment/github-pages/
# as well as https://github.com/shalzz/zola-deploy-action

name: Build and deploy Zola website for GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push (but only for the main branch) or pull request events
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: '*'
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.18.0
        with:
          set-safe-directory: '*'
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          BUILD_THEMES: false
  
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: '*'
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        with:
          set-safe-directory: '*'
        env:
          #TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_THEMES: false

