# This GitHub Actions workflow adapted from https://www.getzola.org/documentation/deployment/github-pages/
name: Build and deploy Zola website for GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: '*'
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_THEMES: false
